### ISSUE TITLE
Review documentation structure

### ISSUE THREAD

**Issue by mebster** [nuvla/documentation#17]
TODO:
- [x] Clarify users (personae)
- [ ] Add simple container deployment with the ui
- [ ] Separate data management from standard container deployment
- [x] Add simple Nuvla deployment for Dave
- [ ] Add best practice for hooking Docker Hub and GitHub for automated image creation (with tags)
- [ ] Synchronise/coordinate with GitHub (READMEs), Website and video description
- [ ] Add NuvlaBox getting started
- [x] Describe invitation mechanism for Bob
- [ ] Provide entry point for module component page (ui) for (since these are not self explanatory):
  - [ ] URLs
  - [ ] Output parameters
  - [ ] Data link

**Comment by cjdcordeiro** [comment]
should the NuvlaBox stuff be here or simply point to a dedicated NuvlaBox docs page?

**Comment by mebster** [comment]
Dave's section includes a page for the installation and registration of NBs. But if we want more detailed documentation, we can either put it under Felix or somewhere else. But I think Felix makes sense such that all the developer docs are together.

**Comment by cjdcordeiro** [comment]
re-structuring proposed in https://github.com/nuvla/documentation/tree/restructuring

waiting for feedback

**Comment by cjdcordeiro** [comment]
this ticket is now closed and obsolete in favor of https://github.com/nuvla/documentation/pull/22.

https://github.com/nuvla/documentation/issues/23 container the new fixes to be worked on
